package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"
)

// The generator owns only the text between these markers. Everything else in the
// README is hand-written and is never touched.
const (
	tableStart = "<!-- cards:table:start -->"
	tableEnd   = "<!-- cards:table:end -->"
)

// updateReadme rewrites the marked block with a plain-markdown twin of the
// charts. The cards cannot carry a hover layer — GitHub serves them through an
// image proxy — so this table is how every plotted value stays readable without
// relying on color or on an interaction that is not available.
func updateReadme(path string, s *Stats) (bool, error) {
	original, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", path, err)
	}

	startIdx := bytes.Index(original, []byte(tableStart))
	endIdx := bytes.Index(original, []byte(tableEnd))
	switch {
	case startIdx < 0 && endIdx < 0:
		return false, nil // nothing to refresh in this README
	case startIdx < 0 || endIdx < 0:
		return false, fmt.Errorf("%s has an unpaired cards:table marker", path)
	case endIdx < startIdx:
		return false, fmt.Errorf("%s has cards:table markers in the wrong order", path)
	}

	replacement := tableStart + "\n\n" + renderTableView(s) + "\n" + tableEnd
	updated := make([]byte, 0, len(original))
	updated = append(updated, original[:startIdx]...)
	updated = append(updated, replacement...)
	updated = append(updated, original[endIdx+len(tableEnd):]...)

	if bytes.Equal(original, updated) {
		return false, nil
	}
	if err := os.WriteFile(path, updated, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

// renderTableView is the accessible twin of the language and activity cards.
func renderTableView(s *Stats) string {
	var b strings.Builder

	b.WriteString("| Language | Share | Tracked size |\n|---|---:|---:|\n")
	if len(s.Languages) == 0 {
		b.WriteString("| _no data_ | — | — |\n")
	}
	for _, l := range s.Languages {
		fmt.Fprintf(&b, "| %s | %.1f%% | %s |\n", l.Name, l.Share*100, humanBytes(l.Bytes))
	}

	b.WriteString("\n| Metric | Last 365 days |\n|---|---:|\n")
	rows := [][2]string{
		{"Contributions", commas(s.TotalContributions)},
		{"Commits", commas(s.Commits)},
		{"Pull requests", commas(s.PullRequests)},
		{"Issues", commas(s.Issues)},
		{"Reviews", commas(s.Reviews)},
		{"Current streak", fmt.Sprintf("%s days", commas(s.CurrentStreak))},
		{"Longest streak", fmt.Sprintf("%s days", commas(s.LongestStreak))},
		{"Public repos", commas(s.PublicRepos)},
		{"Stars earned", commas(s.Stars)},
	}
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s |\n", r[0], r[1])
	}

	fmt.Fprintf(&b, "\n<sub>Generated by <code>./cmd/cards</code> on %s. Public activity only.</sub>\n",
		s.GeneratedAt.Format("2 January 2006"))
	return b.String()
}
