package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"
)

// The generator owns only the text between these markers. Everything else in the
// README is hand-written and is never touched.
const (
	tableStart = "<!-- cards:table:start -->"
	tableEnd   = "<!-- cards:table:end -->"
)

// updateReadme rewrites the marked block with a plain-markdown twin of the
// charts. The cards cannot carry a hover layer — GitHub serves them through an
// image proxy — so this table is how every plotted value stays readable without
// relying on color or on an interaction that is not available.
func updateReadme(path string, s *Stats) (bool, error) {
	original, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("read %s: %w", path, err)
	}

	startIdx := bytes.Index(original, []byte(tableStart))
	endIdx := bytes.Index(original, []byte(tableEnd))
	switch {
	case startIdx < 0 && endIdx < 0:
		return false, nil // nothing to refresh in this README
	case startIdx < 0 || endIdx < 0:
		return false, fmt.Errorf("%s has an unpaired cards:table marker", path)
	case endIdx < startIdx:
		return false, fmt.Errorf("%s has cards:table markers in the wrong order", path)
	}

	replacement := tableStart + "\n\n" + renderTableView(s) + "\n" + tableEnd
	updated := make([]byte, 0, len(original))
	updated = append(updated, original[:startIdx]...)
	updated = append(updated, replacement...)
	updated = append(updated, original[endIdx+len(tableEnd):]...)

	if bytes.Equal(original, updated) {
		return false, nil
	}
	if err := os.WriteFile(path, updated, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", path, err)
	}
	return true, nil
}

// renderTableView is the accessible twin of the language, activity and city cards.
func renderTableView(s *Stats) string {
	var b strings.Builder

	b.WriteString("| Language | Share | Tracked size |\n|---|---:|---:|\n")
	if len(s.Languages) == 0 {
		b.WriteString("| _no data_ | — | — |\n")
	}
	for _, l := range s.Languages {
		fmt.Fprintf(&b, "| %s | %.1f%% | %s |\n", l.Name, l.Share*100, humanBytes(l.Bytes))
	}

	b.WriteString("\n| Metric | Last 365 days |\n|---|---:|\n")
	rows := [][2]string{
		{"Contributions", commas(s.TotalContributions)},
		{"Commits", commas(s.Commits)},
		{"Pull requests", commas(s.PullRequests)},
		{"Issues", commas(s.Issues)},
		{"Reviews", commas(s.Reviews)},
		{"Current streak", fmt.Sprintf("%s days", commas(s.CurrentStreak))},
		{"Longest streak", fmt.Sprintf("%s days", commas(s.LongestStreak))},
		{"Repositories", commas(s.RepoCount)},
		{"Stars earned", commas(s.Stars)},
	}
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s |\n", r[0], r[1])
	}

	// The skyline's own numbers. Every building's height, footprint and lit state
	// is a row here, so the city is readable with images off.
	blocks := s.CityBlocks()
	if len(blocks) > 0 {
		b.WriteString("\n| Building | Commits | Size | Stars | Last push | State | Access |\n|---|---:|---:|---:|---|---|---|\n")
		for _, r := range blocks {
			state := "dormant"
			if r.PushedWithin(s.GeneratedAt, cityFreshWindow) {
				state = "occupied"
			}
			// A private repo is named and measured but never linked: the URL is a
			// 404 for every visitor, and a dead link reads as a broken profile
			// rather than as a closed door.
			name, access := fmt.Sprintf("[%s](https://github.com/%s/%s)", r.Name, s.Login, r.Name), "public"
			if r.Private {
				name, access = r.Name, "private"
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n",
				name, commas(r.Commits), humanBytes(r.SizeKB*1024),
				commas(r.Stars), r.PushedAt.Format("2 Jan 2006"), state, access)
		}
		fmt.Fprintf(&b, "\n<sub>Building height is commits on the default branch, footprint is repo size, "+
			"and a lit facade means pushed within %s. Private repositories are listed for their "+
			"activity only — they are not linked, because the link would 404 for everyone but me.</sub>\n",
			cityAge())
	}

	// plural() appends a bare "s", which "repository" does not take.
	scope := "Public activity only."
	if n := s.PrivateCount(); n > 0 {
		noun := "private repositories"
		if n == 1 {
			noun = "private repository"
		}
		scope = fmt.Sprintf("Includes %d %s, counted for activity but not linked.", n, noun)
	}
	fmt.Fprintf(&b, "\n<sub>Generated by <code>./cmd/cards</code> on %s. %s</sub>\n",
		s.GeneratedAt.Format("2 January 2006"), scope)
	return b.String()
}
